author: "45° 青年"

ShowRssButtonInSectionTermList: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
ShowReadingTime: true
ShowWordCount: true
ShowToc: true # 显示目录
TocOpen: true # 自动展开目录
DateFormat: '2006-01-02'
comments: true
commentsApp: 'giscus'

showStatInSectionTermList: true
showStatInArchiveTitle: true
enableBusuanzi: true
showTransListInSingle: false



